apiVersion: v1
kind: Secret
metadata:
  name: quizapp-secret
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "dev-secret-key-for-docker-compose"
  DATABASE_URL: "postgres://postgres:postgres@postgres:5432/quizapp"
